# Generated by Django 2.1.7 on 2019-02-22 20:04

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kiosk', '0002_auto_20190222_2004'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kiosk',
            name='players',
            field=models.ManyToManyField(blank=True, null=True, to=settings.AUTH_USER_MODEL),
        ),
    ]
